# services:

#   cqrsconceptmongodb:
#     container_name: cqrsconceptmongodb
#     restart: always
#     volumes:
#       - mongo_data:/data/db
#     ports:
#       - "27017:27017"

#   cqrsconceptsqldb:
#     container_name: cqrsconceptsqldb
#     environment:
#       SA_PASSWORD: "SwN12345678"
#       ACCEPT_EULA: "Y"
#     restart: always
#     ports:
#       - "1433:1433"

#   cqrsconcept.api:
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_HTTP_PORTS=8080
#     ports:
#       - "8080"
