
services:

  cqrsconceptmongodb:
    image: mongo
    container_name: cqrsconceptmongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

#   cqrsconcept.api:
#     image: ${DOCKER_REGISTRY-}cqrsconceptapi
#     build:
#       context: .
#       dockerfile: src/CQRSConcept.Api/Dockerfile

volumes:
  mongo_data:
